### ISSUE TITLE
Can not work.

### ISSUE THREAD

**Issue by baofengyv** [erhangundogan/sql2mongodb#2]
$ node app.js
C:\Users\b\Desktop\sql2mongodb-master\node_modules\_socket.io@0.9.13@socket.io\lib\store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (C:\Users\b\Desktop\sql2mongodb-master\node_modules\_socket.io@0.9.13@socket.io\lib\store.js:35:42)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\b\Desktop\sql2mongodb-master\node_modules\_socket.io@0.9.13@socket.io\lib\manager.js:16:13)
    at Module._compile (module.js:662:30)

**Comment by andresfiloso** [comment]
same error

``` javascript
$ node app.js
C:\Users\andres\node_modules\socket.io\lib\store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                         ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (C:\Users\andre\node_modules\socket.io\lib\store.js:35:42)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\andre\node_modules\socket.io\lib\manager.js:16:13)
    at Module._compile (module.js:652:30)`
